### ISSUE TITLE
UpperAir_Obs DataArray issues

### ISSUE THREAD

**Issue by cturnbull23** [Unidata/python-training#119]
macOS Big Sur 11.2.3, Python 3.8, metpy 1.0.

The temperature conversion to degrees celsius results in an attribute error: 'DataArray' object has no attribute 'to'
<img width="846" alt="Screen Shot 2021-04-16 at 6 31 06 PM" src="https://user-images.githubusercontent.com/76788494/115090095-ef9ff580-9ee1-11eb-8a7a-1fb39af8fa11.png">

and 'DataArray' object has no attribute 'm' for smooth_hght.m

<img width="996" alt="Screen Shot 2021-04-16 at 6 35 45 PM" src="https://user-images.githubusercontent.com/76788494/115090345-984e5500-9ee2-11eb-85d1-2d56ef9fa5ba.png">

**Comment by dopplershift** [comment]
Thanks for the report. Looks like this was missed by #113. This will definitely get caught when we get the site back to automatically building and deploying.

**Comment by wxguy** [comment]
Still facing the same issue. Is there a solution to this?

**Comment by dopplershift** [comment]
We've been working on migrating these resources to be a "MetPy Cookbook" within [Project Pythia's](https://projectpythia.org]) collection of Python resources, and sunsetting this particular repository. The [updated version of this notebook](https://projectpythia.org/metpy-cookbook/notebooks/synoptic/Upperair_Obs.html) there should work for you. Let us know if that's not the case.

**Comment by wxguy** [comment]
> We've been working on migrating these resources to be a "MetPy Cookbook" within [Project Pythia's](https://projectpythia.org%5D) collection of Python resources, and sunsetting this particular repository. The [updated version of this notebook](https://projectpythia.org/metpy-cookbook/notebooks/synoptic/Upperair_Obs.html) there should work for you. Let us know if that's not the case.

Working. Thank you.

**Comment by dopplershift** [comment]
Closing since the updated version is in the metpy cookbook on Project Pythia, and we're not planning on updating in this repo.
