### ISSUE TITLE
How could we set up South Polar Projection 

### ISSUE THREAD

**Issue by shifei90** [Unidata/python-training#29]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
* a description of the issue with the steps needed to reproduce it

If you have a general question about the software, please view our [Suggested Support Process](https://www.unidata.ucar.edu/support/#process).

**Comment by dopplershift** [comment]
This question is probably better asked on https://stackoverflow.com or the [cartopy issue tracker](https://github.com/SciTools/cartopy/issues/new).
