### ISSUE TITLE
QG Notebook broken

### ISSUE THREAD

**Issue by dopplershift** [Unidata/python-training#90]
The QG notebook was completely busted by metpy 1.0rc1. Not sure if it's a simple update, or if there's something not-so-good in the rc. (heads up @jthielen )

**Comment by jthielen** [comment]
I'll have to take a closer look once https://github.com/Unidata/MetPy/pull/1304 / https://github.com/Unidata/MetPy/pull/1325 are in, but my initial guess from a quick read through is that that notebook assumes `mpcalc.smooth_n_point` outputs pint Quantities when supplied `xarray.DataArray`, which changed to outputting `xarray.DataArray` with https://github.com/Unidata/MetPy/pull/1223.

**Comment by dopplershift** [comment]
That makes sense, I can run with that and see what happens. This is the first time I've tried to use the RC in a workshop, and I did that because some combination of xarray and pint updates broke something in getting the longitude coords.

**Comment by dopplershift** [comment]
Fixed in 455ffa0.
